### ISSUE TITLE
Bug: Switching between worlds overlays map markers onto unrelated map

### ISSUE THREAD

**Issue by rakheepatel** [Mydayyy/Valheim-ServerSideMap#41]
There's a buggy behaviour where jumping between worlds on the same game session overlays map pins, i.e. if I log out of world1 and log into world2, then I see world1's map markers overlaid on world2's map. Only way to fix it right now is to quit Valheim and restart in world2.

1. With the mod _(v1.3.1)_ loaded, start the game and go into a world with map markers
2. Open the map
3. Close the map and **Log Out** (retain the game session)
4. Open another world with map markers using a character who has made markers there _(it could be the same character, or maybe you have made one for each world. I used a different character)_
5. Open the map. Notice there are markers that shouldn't be here, most obvious when markers appear in fogged parts of the map

Expected result:
Map should only show markers for its own map

Actual result:
Map is showing markers for another map

Screenshots:

Map 1 Character 1:
![image](https://user-images.githubusercontent.com/5573174/119582635-3b5e8c80-be08-11eb-8592-232478919749.png)

Map 2 Character 2: 
![image](https://user-images.githubusercontent.com/5573174/119582652-46192180-be08-11eb-8c47-69970336c938.png)

**Comment by Mydayyy** [comment]
Greetings,

this should too be fixed with the new rc: rc-1.3.4.

Best Regards
Mydayyy

**Comment by rakheepatel** [comment]
Maps now retain their own markers, however I found that some of my markers are missing. Here are some before and after screenshots:

Before rc-1.3.4 Map 1 Character 1:
![image](https://user-images.githubusercontent.com/5573174/119582635-3b5e8c80-be08-11eb-8592-232478919749.png)

After rc-1.3.4 Map 1 Character 1:
![Vbugmap3](https://user-images.githubusercontent.com/5573174/119759213-3292b700-beeb-11eb-8ee5-280aabc0a00a.png)

Maybe something got lost in the translation with ignoring local dupes?

**Comment by Mydayyy** [comment]
Looked into this and I can not reproduce any loss of pins so far. Is this a permanent loss or do they show up again?

**Comment by rakheepatel** [comment]
Hey, sorry for the delayed reply. 
The loss of markers is permanent, they didn't come back. I have no way of knowing whether they went missing because of a download error or something else. I even switched the dll back to the previous one, but the markers were still missing. Switching between sessions has no effect on bringing back the missing markers, switching sessions is retaining markers of the respective maps as per the other issue you fixed.

In the grand scheme of things I'm only playing this casually so I'm not heartbroken about my markers missing, but I'd probably get some others to test this release a bit more. I'd hate for this to be merged only to cause issues with other players' map markers too.
